headless = true
quit_on_end = true
valid_path_names = ["path", "filename", "video", "video_path"]
valid_descriptions = ["description", "desc", "caption"]
implicit_wait = 5
explicit_wait = 60
uploading_wait = 180

add_hashtag_wait = 5

supported_file_types = ["mp4", "mov", "avi", "wmv", "flv", "webm", "mkv", "m4v", "3gp", "3g2", "gif", "ts"]

max_description_length = 150

[paths]
main = "https://www.tiktok.com/"
login = "https://www.tiktok.com/login/phone-or-email/email"
upload = "https://www.tiktok.com/creator-center/upload?lang=en"

[disguising]
user_agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Mobile/15E148 Safari/604.1'

[selectors]

	[selectors.login]
	username_field = "//input[@name='username' or @name='email']"
	password_field = "//input[@type='password']"
	login_button = "//button[@type='submit' or contains(text(), 'Log in')]"
	
	alert_user_if_failed = true
	
	cookie_of_interest = "sessionid"
	
	[selectors.upload]
	iframe = "//iframe"
	
	split_window = "//button[./div[text()='Not now']]"
	upload = "//input[@type='file'] | //input[contains(@accept, 'video')]"
	upload_finished = "//div[contains(@class, 'btn-cancel')]"
 	upload_confirmation = "//div[@title]"
 	processing = "//div[contains(@class, 'processing')] | //div[contains(@class, 'uploading')] | //div[contains(text(), 'Processing')] | //div[contains(text(), 'Uploading')] | //div[contains(@class, 'progress')]"
 	complete = "//div[contains(@class, 'complete')] | //div[contains(@class, 'success')] | //div[contains(text(), 'Complete')] | //div[contains(text(), 'Success')]"
	description = "//div[@contenteditable='true']"

	visibility = "//div[@class='tiktok-select-selector']"
	options = ["Public", "Friends", "Private"]

	mention_box = "//div[contains(@class, 'mention-list-popover')]"
	mention_box_user_id = "//span[contains(@class, 'user-id')]"

	comment = "//label[.='Comment']/following-sibling::div/input | //div[contains(text(), 'Comments')]//following::input[@type='checkbox']"
	duet = "//label[.='Duet']/following-sibling::div/input | //div[contains(text(), 'Duet')]//following::input[@type='checkbox']"
	stitch = "//label[.='Stitch']/following-sibling::div/input | //div[contains(text(), 'Stitch')]//following::input[@type='checkbox']"

	post = "//button[@data-e2e='post_video_button'] | //button[contains(text(), 'Post')] | //button[contains(@class, 'post')] | //button[@type='submit']"
	post_confirmation = "//div[contains(text(), 'Your video has been uploaded') or contains(text(), '视频已发布') or contains(@class, 'success') or contains(@class, 'complete') or contains(text(), 'Posted')]"

	[selectors.upload.cookies_banner]
		banner = "tiktok-cookie-banner"
		button = "div.button-wrapper"
